version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: song_list_db
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: matanv1405
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
